### ISSUE TITLE
Connect Cloud Run to SQL (or AlloyDB) database

### ISSUE THREAD

**Issue by LilaKelland** [PHACDataHub/cloudrun-deployment-example#11]
With the networking org constraints, there have been issues with VPC network - we need to connect Cloud Run with the database: work to get the auth proxy to work (https://cloud.google.com/sql/docs/mysql/connect-run).  There's also a [docker proxy image](https://cloud.google.com/sql/docs/mysql/connect-auth-proxy#connecting-docker) to use for testing.

**Comment by LilaKelland** [comment]
We have this working here using socket, and the cloud-sql-proxy for initial migrations.  Still need to set up for testing, and testing migrations

**Comment by Stephen-ONeil** [comment]
Solved in the CPHO project, see [this PR](https://github.com/PHACDataHub/cpho-phase2/pull/50)
