### ISSUE TITLE
Determine workflow for migrations 

### ISSUE THREAD

**Issue by LilaKelland** [PHACDataHub/cloudrun-deployment-example#12]
We can use [migration.yaml](https://cloud.google.com/python/django/run#:~:text=The%20cloudmigrate.yaml%20file%20performs) files.  How do these fit into the CI/CD workflow - ie testing, working with cloud build trigger etc.

**Comment by LilaKelland** [comment]
Clarifying this as we're using the cloud build triggers now. Where do we put testing - we have GitHub workflow that runs tests (but needs to be cleaned/ updated), but with the trigger, the github workflow and cloud build process run in parallel, and the container will be deployed even if tests failed.  We can lock down main branch, and run tests on pull request, but should we be putting them inside the cloudbuild.yaml as well?

**Comment by LilaKelland** [comment]
https://cloud.google.com/blog/topics/developers-practitioners/running-database-migrations-cloud-run-jobs

**Comment by Stephen-ONeil** [comment]
Conversation moving to https://github.com/PHACDataHub/cpho-phase2/issues/64
