### ISSUE TITLE
Use a minimalist base image

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/cloudrun-deployment-example#16]
While the current image is already using python-slim, it'd be good to reduce the attack surface further with some kind of minimalist docker image. While Alpine linux is a popular choice, it doesn't go quite as far as the [Distroless](https://github.com/GoogleContainerTools/distroless)  images do, and [historically doesn't play nice with Python](https://pythonspeed.com/articles/alpine-docker-python/) which seems to need [Glibc](https://www.gnu.org/software/libc/) to work properly. 

[Chainguards Python image](https://www.chainguard.dev/unchained/chainguard-image-now-available-for-python-3-11) seems pretty ideal to use as a base image for our Django setup, taking the ideas of distroless even further.

We can explore/verify the contents of a docker image with [`dive`](https://github.com/wagoodman/dive).

**Comment by Stephen-ONeil** [comment]
[Here's](https://github.com/PHACDataHub/cpho-phase2/blob/c9637d50557a27a68b3d6ba3452d63189871ecf4/server/Dockerfile) a functioning example with Alpine, although it's not been thoroughly put through it's paces for run-time issues. It does solve the glibc issue with a separate "builder" layer though, installing glibc and other dependencies to build the package wheels, which are then used in a lighter weight run time layer.

**Comment by Stephen-ONeil** [comment]
Moved to CPHO repo
