### ISSUE TITLE
Add OpenTelemetry

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/cloudrun-deployment-example#7]
[OpenTelemetry](https://opentelemetry.io/) is an open observability standard. [Google's Cloud Trace works with OT](https://cloud.google.com/trace/docs/setup/python-ot) and there is [a library](https://opentelemetry-python.readthedocs.io/en/latest/examples/django/README.html) that automatically instruments Django applications. We should add this to the demo, so we can explore the options for monitoring and observability.

The result of this instrumentation is a detailed look at performance across the entire stack:
![trace-demo](https://github.com/PHACDataHub/cloudrun-deployment-example/assets/109692/dba7e318-245e-41c8-9b3a-d0197aec087c)

**Comment by LilaKelland** [comment]
Adding another link: https://github.com/GoogleCloudPlatform/opentelemetry-cloud-run

**Comment by Stephen-ONeil** [comment]
See CPHO issue: https://github.com/PHACDataHub/cpho-phase2/issues/23
