### ISSUE TITLE
Look at incorporating Identity Aware Proxy

### ISSUE THREAD

**Issue by LilaKelland** [PHACDataHub/cloudrun-deployment-example#9]
Mike provided this [link](https://www.youtube.com/watch?v=ayTGOuCaxuc) that demonstrates how to use Identity Aware Proxy (IAP) to allow only internal users (or list of approved users) to access the Cloud Run application.  Should we set this up in this repo?

**Comment by Stephen-ONeil** [comment]
Moved to CPHO [here](https://github.com/PHACDataHub/cpho-phase2/issues/82)
